ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ua.ukma.edu.danki.ApplicationKt.module
jwt:
  secret:
    "$JWT_SECRET:secret"
  issuer:
    "$JWT_ISSUER:https://Danki"
  validity:
    "$JWT_VALIDITY:3600000000"
db:
  driver:
    "$DB_DRIVER:org.h2.Driver"
  url:
    "$DB_URL:jdbc:h2:file:./build/db"